version: '3.8'

services:
  # PostgreSQL Datenbank
  postgres:
    image: postgres:14-alpine
    container_name: fmsv-dev-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: fmsv_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # pgAdmin (Datenbank-Verwaltung)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: fmsv-dev-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: dev@pgadmin.local
      PGADMIN_DEFAULT_PASSWORD: dev123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "8080:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres

volumes:
  postgres-data:
    driver: local
  pgadmin-data:
    driver: local

networks:
  default:
    name: fmsv-dev-network
